spring:

  profiles:
    active: prod


  jpa:
    hibernate:
      ddl-auto: update

  resources:
    static-locations: "file:webapp/src/,file:webapp/bower_components/"

  thymeleaf:
    cache: false

resources:
  image-folder: images/avatars/
  api-url: http://localhost:8080
  web-url: http://localhost:8080
remember-me:
  token: SN_REMEMBER_TOKEN
  cookie: SN_REMEMBER_ME_COOKIE

